package com.finaxis.platform.architecture

import com.tngtech.archunit.core.domain.JavaClasses
import com.tngtech.archunit.core.importer.ClassFileImporter
import com.tngtech.archunit.core.importer.ImportOption
import com.tngtech.archunit.lang.syntax.ArchRuleDefinition.noClasses
import org.junit.jupiter.api.Test
import java.util.UUID
import kotlin.test.assertEquals

/**
 * Guards the identifier-generation contract: the application owns primary-key generation, clients
 * never supply it, and every generated identifier is a time-ordered UUIDv7 rather than a random
 * UUIDv4. See ADR 0015 and the `id UUID PRIMARY KEY DEFAULT uuidv7()` convention in
 * `V1__foundation_schema.sql`.
 */
class IdentifierGenerationRuleTests {
    private val productionClasses: JavaClasses =
        ClassFileImporter()
            .withImportOption(ImportOption.Predefined.DO_NOT_INCLUDE_TESTS)
            .importPackages("com.finaxis.platform")

    @Test
    fun `production code never generates random version 4 identifiers`() {
        noClasses()
            .that()
            .resideOutsideOfPackage("com.finaxis.platform.jooq..")
            .should()
            .callMethod(UUID::class.java, "randomUUID")
            .because(
                "identifiers must be time-ordered uuidv7 values so primary-key and " +
                    "idempotency-key inserts append to the right edge of the index; use the " +
                    "database DEFAULT uuidv7() or com.finaxis.platform.common.id.uuidV7()",
            ).check(productionClasses)
    }

    @Test
    fun `no inbound request DTO exposes a client suppliable primary key`() {
        val offenders =
            productionClasses
                .asSequence()
                .filter { it.packageName.contains(".adapter.inbound.web") }
                .filter { it.simpleName.endsWith("Request") }
                .filter { candidate -> candidate.fields.any { it.name == "id" } }
                .map { it.simpleName }
                .sorted()
                .toList()

        assertEquals(
            emptyList(),
            offenders,
            "primary keys are generated by the application, never supplied by clients",
        )
    }
}
